#!/bin/zsh
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

export TICKET_API_PORT="${TICKET_API_PORT:-8790}"
export TICKET_API_BIND_HOST="${TICKET_API_BIND_HOST:-127.0.0.1}"
export TICKET_API_LOCAL_BASE_URL="${TICKET_API_LOCAL_BASE_URL:-http://127.0.0.1:${TICKET_API_PORT}}"
export TICKET_API_HEALTHCHECK_BASE_URL="${TICKET_API_HEALTHCHECK_BASE_URL:-http://127.0.0.1:${TICKET_API_PORT}}"
export TICKETS_DB_PATH="${TICKETS_DB_PATH:-$REPO_DIR/data/ticket-platform-v2.db}"
export TICKET_BACKUP_BEFORE_START="${TICKET_BACKUP_BEFORE_START:-false}"
export TICKET_INTERNAL_POLLERS_ENABLED="${TICKET_INTERNAL_POLLERS_ENABLED:-false}"
export TICKET_DISPATCH_POLL_INTERVAL_MS="${TICKET_DISPATCH_POLL_INTERVAL_MS:-5000}"
export TICKET_NOTIFY_POLL_INTERVAL_MS="${TICKET_NOTIFY_POLL_INTERVAL_MS:-5000}"
export TICKET_AUDIT_POLL_INTERVAL_MS="${TICKET_AUDIT_POLL_INTERVAL_MS:-30000}"

: "${NODE_BIN:=/opt/homebrew/bin/node}"
exec "$NODE_BIN" api/server.js
